#!/usr/bin/ruby
packs=""
exit if ARGV.count==0
ARGV.each do |arg|

	out=%x(LANG="C" pacman -Si #{arg})
	next if out.empty?
	
	packs+="#{arg} "
	
	lines=out.split "\n"
	first=(lines[10].split ":")[1].strip 
	
	next if first == "None"

	packs+="#{first} "

	i=11
	while lines[i][0]==" " do
		packs+=(lines[i].split ":")[0].strip + " "
		i+=1
	end
end
exec ("pacman -S #{packs}")
