#! /bin/sh

activeOutput1=$(xrandr | grep -E "connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | sed -n 1p)

activeOutput2=$(xrandr | grep -E "connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | sed -n 2p)

bspc config click_to_focus on
bspc config focus_follows_pointer on
bspc config pointer_motion_interval 15

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor $activeOutput1 -d 1 2 3 4 5 6 
bspc monitor $activeOutput2 -d 7 8 9 0

bspc config border_width         3
bspc config window_gap          5

#928374

bspc config active_border_color '#1f222d'
bspc config normal_border_color '#1f222d'
bspc config focused_border_color '#FF6200'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Atom desktop=^3
bspc rule -a Chromium desktop=^1
bspc rule -a Firefox desktop=^1
bspc rule -a Clementine desktop=^4
#bspc rule -a Xfce4-terminal desktop=^2
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#############
# Autostart #
#############
sxhkd &
compton -b
$HOME/.config/polybar/launch.sh
colorcorrection
feh --bg-scale '/home/davide/Immagini/Taylor Swift Wallpapers - Imgur/22 - nqvI0Jy.jpg'
export _JAVA_AWT_WM_NONREPARENTING=1
mpd &
nm-applet &
