#! /bin/sh

# Get first monitor name
activeOutput1=$(xrandr | grep -E "connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | sed -n 1p)

# Get second monitor name
activeOutput2=$(xrandr | grep -E "connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | sed -n 2p)



# Pointer settings
bspc config click_to_focus on
bspc config focus_follows_pointer on
bspc config pointer_motion_interval 15

# Monitor settings
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor $activeOutput1 -d 1 2 3 4 5 6 
bspc monitor $activeOutput2 -d 7 8 9 0

bspc config border_width         2
bspc config window_gap          5

BG=$(xrdb -query | grep "*.background:" | awk '{print $2}')
FG=$(xrdb -query | grep "*.foreground:" | awk '{print $2}')
COLOR0=$(xrdb -query | grep "*.color0:" | awk '{print $2}')
COLOR1=$(xrdb -query | grep "*.color1:" | awk '{print $2}')
COLOR2=$(xrdb -query | grep "*.color2:" | awk '{print $2}')
COLOR3=$(xrdb -query | grep "*.color3:" | awk '{print $2}')
COLOR4=$(xrdb -query | grep "*.color4:" | awk '{print $2}')
COLOR5=$(xrdb -query | grep "*.color5:" | awk '{print $2}')
COLOR6=$(xrdb -query | grep "*.color6:" | awk '{print $2}')
COLOR7=$(xrdb -query | grep "*.color7:" | awk '{print $2}')
COLOR8=$(xrdb -query | grep "*.color8:" | awk '{print $2}')
COLOR9=$(xrdb -query | grep "*.color9:" | awk '{print $2}')
COLOR10=$(xrdb -query | grep "*.color10:" | awk '{print $2}')
COLOR11=$(xrdb -query | grep "*.color11:" | awk '{print $2}')
COLOR12=$(xrdb -query | grep "*.color12:" | awk '{print $2}')
COLOR13=$(xrdb -query | grep "*.color13:" | awk '{print $2}')
COLOR14=$(xrdb -query | grep "*.color14:" | awk '{print $2}')
COLOR15=$(xrdb -query | grep "*.color15:" | awk '{print $2}')

# Colors
bspc config active_border_color $BG
bspc config normal_border_color $BG
bspc config focused_border_color $COLOR9

#bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Rules
bspc rule -a Atom desktop=^3
bspc rule -a Chromium desktop=^1
bspc rule -a Google-chrome:www.netflix.com desktop=^6
bspc rule -a Firefox desktop=^1
bspc rule -a Clementine desktop=^4
bspc rule -a Zathura desktop=^3 state=tiled
#bspc rule -a URxvt desktop=^2
#bspc rule -a Xfce4-terminal desktop=^2
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Ristretto state=floating
bspc rule -a feh state=floating
bspc rule -a VirtualBox desktop=^5 state=floating
bspc rule -a Firefox:Places state=floating
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Autostart 
sxhkd &
compton -b
$HOME/.config/polybar/launch.sh
#colorcorrection
#feh --bg-scale '/home/davide/Immagini/Taylor Swift Wallpapers - Imgur/22 - nqvI0Jy.jpg'
feh --bg-scale '/home/davide/Immagini/bonsai.jpg'
#export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D
#mpd &
nm-applet &
