#!/bin/bash

#
#  ▄▄
#  ██
#  ██▄███▄   ▄▄█████▄  ██▄███▄  ██      ██ ████▄██▄   ██▄████   ▄█████▄
#  ██▀  ▀██  ██▄▄▄▄ ▀  ██▀  ▀██ ▀█  ██  █▀ ██ ██ ██   ██▀      ██▀    ▀
#  ██    ██   ▀▀▀▀██▄  ██    ██  ██▄██▄██  ██ ██ ██   ██       ██
#  ███▄▄██▀  █▄▄▄▄▄██  ███▄▄██▀  ▀██  ██▀  ██ ██ ██   ██       ▀██▄▄▄▄█
#  ▀▀ ▀▀▀     ▀▀▀▀▀▀   ██ ▀▀▀     ▀▀  ▀▀   ▀▀ ▀▀ ▀▀   ▀▀         ▀▀▀▀▀
#                      ██
#

"$HOME/.config/bspwm/autostart" && wait

bspc monitor \^1 -d www dev pdf uni chat ph misc
bspc monitor \^2 -d VIII IX X
#bspc monitor -d 1 2 3 4 5 6 7 8 #9 10
#$HOME/.config/bspwm/enforce_monitor_position eDP-1 \^1 &

_() { bspc config "$@";  }
R() { bspc rule -a "$@"; }
L() { bsp-layout remove "$3"; bsp-layout "$@"; }

# theme
_ top_padding                 36
_ border_width                "4"
_ window_gap                  "10"
_ normal_border_color         "#2E3440"
_ focused_border_color        "#BF616A"
_ active_border_color         "#B48EAD"
#_ floating.normal.color       "#4C566A"
#_ floating.active.color       "#BF616A"

# options
_ remove_disabled_monitors    true
_ remove_unplugged_monitors   true
_ focus_follows_pointer       true
_ split_ratio                 0.50
_ borderless_monocle          true
_ gapless_monocle             true
#_ paddingless_monocle         true
_ single_monocle              false
#_ history_aware_focus         true
#_ normal_frame_opacity        0.95
#_ focused_frame_opacity       1.0
_ external_rules_command      "$HOME/.config/bspwm/external_rules"

# reset rules
bspc rule -r "*"

function receptacles () {
  for i in $(bspc query -N -n '.leaf.!window.local'); do bspc node $i -k; done
  if [[ ! $(bspc query -N -d chat) ]]; then   # test if workspace 3 is empty

    # first clean all receptacles
    #for i in $(bspc query -N -n '.leaf.!window.local'); do bspc node $i -k; done

    # receptacles
    bspc node @chat:/ -i
    bspc node @chat:/ -o 0.20 -p east -i
    R "TelegramDesktop" -o node=@chat:/1 state=pseudo_tiled desktop=chat rectangle=360x1080+0+0
    R "Alacritty" -o node=@chat:/2 state=tiled
   #telegram-desktop &
    #$TERMINAL &
  fi
}
#receptacles


# set layouts
L set rtall pdf -- --master-size 0.64
#L set tall chat -- --master-size 0.21

# window->tag rules
R 'firefox'                             desktop=www focus=on
R 'Chromium'                            desktop=www focus=on
R 'spotify'                             desktop=misc
R 'discord'                             desktop=misc
R "Gnome-boxes:gnome-boxes"             desktop=ph

# generic rules
R 'firefox:Places'                      state=floating
R 'firefox:Browser'                      state=floating
R 'Emoji Selector'                  state=floating
#R "Org.gnome.Nautilus" state=pseudo_tiled
R "Org.gnome.NautilusPreviewer" state=floating
R "Zathura" state=tiled node=@pdf:/2
R "Viewnior" state=floating
#R "TelegramDesktop:telegram-desktop:Media viewer" state=fullscreen
#R "TelegramDesktop" -o node=@chat:/1 state=pseudo_tiled desktop=chat rectangle=360x1080+0+0
#R "kitty" -o node=@chat:/2 state=tiled
R "dolphin" state=pseudo_tiled

# window sizes
R 'kitty' rectangle=800x600+0+0

# other floating windows
R "Eog"                state=floating
R "feh"                state=floating
R "sxiv"               state=floating
R "Transmission-gtk"   state=floating
R "systemsettings"     state=floating center=on
R "Wpg"                state=floating

# no borders
R "albert"             border=off focus=on

