#!/bin/sh

"$HOME/.local/bin/autostart.sh"
"$HOME/.config/herbstluftwm/config"

# load layout
while read -r line; do
  tag="$(echo "$line" | grep -o "^[[:digit:]]\+:")"
  layout="$(echo "$line" | cut -c $((${#tag}+2))-)"
  echo "herbstclient load $(echo "$tag" | cut -c 1,$((${#tag}-1))) "$layout""
  herbstclient load $(echo "$tag" | cut -c 1,$((${#tag}-1))) "$layout"
done < "$HOME/.config/herbstluftwm/layout"
#notify-send "Layout loaded"

