#!/bin/bash
GVT_PCI=0000:00:02.0
GVT_GUID=532786aa-940a-43cc-a3c5-3daa1f8a855f
MDEV_TYPE=i915-GVTg_V5_4
DOMAIN=win10

if [ $# -ge 3 ]; then
    if [ $1 = "$DOMAIN" -a $2 = "prepare" -a $3 = "begin" ]; then
       sudo sh -c "echo $GVT_GUID > /sys/bus/pci/devices/$GVT_PCI/mdev_supported_types/$MDEV_TYPE/create"
    elif [ $1 = "$DOMAIN" -a $2 = "release" -a $3 = "end" ]; then
        sudo sh -c "echo 1 > /sys/bus/pci/devices/$GVT_PCI/$GVT_GUID/remove"
    fi
fi
